version: "3.8"

services:
  mkcert:
    image: fjogeleit/mkcert
    container_name: mkcert
    command: ["mkcert", "-install"]
    volumes:
      - ./certs:/root/.local/share/mkcert
    networks:
      - cert-net

  traefik:
    image: traefik:v3.2 # latest stable version
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
    networks:
      - cert-net

networks:
  cert-net:
    driver: bridge
