[package]
name = "roadsense-consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = "2.2.6"
dotenv = "0.15.0"
env_logger = "0.11.5"
futures-lite = "2.5.0"
lapin = "2.5.0"
log = "0.4.22"
tokio = { version = "1.41.1", features = ["full"] }
